### ISSUE TITLE
python test_gcdcDrawRect.py gets error

### ISSUE THREAD

**Issue by alec178** [wxWidgets/wxPython#33]
Hi,
I perform the command: `python test_gcdcDrawRect.py`, and gets the error message:

```
  File "test_gcdcDrawRect.py", line 20, in OnPaint
    if CLIP: dc.SetClippingRect(r)
AttributeError: 'GCDC' object has no attribute 'SetClippingRect''
```

Is there any lib I shall install in advance?

**Comment by RobinD42** [comment]
Since you don't mention platform or version I'll just have to guess. You are probably using the new "Phoenix" version of wxPython (4.0.x) with an unreleased test sample from the Classic version of wxPython. As it says on the root project page here, "This is the repository for "Classic" wxPython. All new development is happening in the Phoenix project at https://github.com/wxWidgets/Phoenix"

In the new version that method is called `SetClippingRegion` since the old artificially renamed methods are no longer needed for overloading. See https://docs.wxpython.org/wx.DC.html?highlight=setclipping#wx.DC.SetClippingRegion and https://docs.wxpython.org/MigrationGuide.html

**Comment by alec178** [comment]
After replaceing `SetClippingRect` by `SetClippingRegion`, it works!
Thanks!
