### ISSUE TITLE
Size problem with wxStaticText

### ISSUE THREAD

**Issue by kdschlosser** [wxWidgets/wxPython#34]
OS - Windows 7 SP2 x64
Python Version - 2.7.15
wxPython Version - 3.0.2.0 msw (classic)

I am not sure where this problem is stemming from if it iis wxPython or wxWidgets. I use wxPython directly so this is where i am posting the bug report.

Setting the height of a wx.StaticText control does not work properly.
The height of the item never changes visually. but when you call the GetSize method it returns the set height.

here is some sample code to replicate the problem.

```python
from __future__ import print_function
import wx

app = wx.App()

class Frame(wx.Frame):

    def __init__(self):
        wx.Frame.__init__(self, None, -1, size=(600, 400))

        sizer = wx.BoxSizer(wx.VERTICAL)

        self.st1 = wx.StaticText(self, -1, 'This is some test text line 1')
        self.st2 = wx.StaticText(self, -1, 'This is some test text line 2')

        sizer.Add(self.st1, 0, wx.ALL, 5)
        sizer.Add(self.st2, 0, wx.ALL, 5)

        self.SetSizer(sizer)


frame = Frame()
frame.Show()

print('line 1 size before setting height: ', frame.st1.GetSize())

frame.st1.SetSize((frame.st1.GetSize()[0], 500))

frame.Refresh()
frame.Update()

print('line 1 size after setting height: ', frame.st1.GetSize())
print('You did not see a change in GUI at all')

app.MainLoop()
```

**Comment by RobinD42** [comment]
You're missing a few things.

- First, `Refresh` and `Update` only deal with painting the object, not managing the layout of the object's children.

- Next, the way sizers work is when a layout is triggered they look at the child items' best size (which is usually based on the child's type and content) and the child's minsize, which is set programatically. After the sizer has calculated everything then it changes the position and actual size of the items it is managing. What you are changing with `SetSize` is the item's actual size, and so when the sizer does its work that actual size is overridden by the sizer.

- Finally, when you call `MainLoop` there are some initial events, including size events, which is where the sizer does the layout by default. So in other words, you are changing the size, printing the new size, and then later after `MainLoop` starts then the size is changed back, so that is why the size/position you see does not match what is printed.

I've tweaked your sample a litte to address these issues. Notice that it calls `Layout` to trigger a new layout with the new size, uses `SetMinSize` to control how the sizer will manage the layout, and delays the changes until after `MainLoop` has started. 

You may also want to give the Widget Inspection Tool a try (commented out in the code) as it is a good way to help explore and learn how things work, and also help to diagnose layout issues like this.


```python
from __future__ import print_function
import wx

app = wx.App()

class Frame(wx.Frame):

    def __init__(self):
        wx.Frame.__init__(self, None, -1, size=(600, 400))

        sizer = wx.BoxSizer(wx.VERTICAL)

        self.st1 = wx.StaticText(self, -1, 'This is some test text line 1')
        self.st2 = wx.StaticText(self, -1, 'This is some test text line 2')

        sizer.Add(self.st1, 0, wx.ALL, 5)
        sizer.Add(self.st2, 0, wx.ALL, 5)

        self.SetSizer(sizer)

frame = Frame()
frame.Show()

def after_startup():
    print('line 1 size before setting height: ', frame.st1.GetSize())

    frame.st1.SetMinSize((frame.st1.GetSize()[0], 250))
    frame.Layout()

    print('line 1 size after setting height: ', frame.st1.GetSize())

wx.CallAfter(after_startup)
# import wx.lib.inspection
# wx.lib.inspection.InspectionTool().Show()
app.MainLoop()
```
